name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the sections below to help us understand and reproduce the issue.

  - type: checkboxes
    id: search
    attributes:
      label: "Search existing issues"
      description: "Please search existing issues to avoid duplicates"
      options:
        - label: "I have searched existing issues and this is not a duplicate"
          required: true

  - type: textarea
    id: description
    attributes:
      label: "Bug Description"
      description: "A clear and concise description of what the bug is"
      placeholder: "Describe the bug..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: "Steps to Reproduce"
      description: "Steps to reproduce the behavior"
      placeholder: |
        1. Configure with '...'
        2. Run command '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "What you expected to happen"
      placeholder: "Describe what should have happened..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "Actual Behavior"
      description: "What actually happened"
      placeholder: "Describe what actually happened..."
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: "Version"
      description: "What version are you running? (`rust-research-mcp --version`)"
      placeholder: "0.4.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: "Operating System"
      description: "What operating system are you using?"
      placeholder: "macOS 14.0, Ubuntu 22.04, Windows 11, etc."
    validations:
      required: true

  - type: input
    id: rust-version
    attributes:
      label: "Rust Version"
      description: "What Rust version are you using? (`rustc --version`)"
      placeholder: "rustc 1.70.0"

  - type: textarea
    id: logs
    attributes:
      label: "Relevant Logs"
      description: "Any relevant log output (please redact sensitive information)"
      render: text
      placeholder: "Paste log output here..."

  - type: textarea
    id: additional
    attributes:
      label: "Additional Context"
      description: "Any additional context that might be helpful"
      placeholder: "Add any other context about the problem here..."

  - type: checkboxes
    id: terms
    attributes:
      label: "Legal and Ethical Use"
      description: "Please confirm this bug report relates to legitimate academic use"
      options:
        - label: "This issue relates to legitimate academic research use only"
          required: true